### ISSUE TITLE
Some questions after reading the readme file

### ISSUE THREAD

**Issue by stiefdirckx** [umbraco/vsts-uaas-deploy-task#3]
@sitereactor Since I'm a fan of VSTS I'm interested in using this task even though I haven't yet used UaaS before. After reading the readme file I still have a few questions before I'll try it out and make the jump to UaaS.
- The UaaS documentation on Our advises to use a Website project with a separate Class Library project for custom code but this task uses a single Web Application project. Does this influence other UaaS practices?
- As connection string you say to use a SQL CE database on the local environment. I suppose a regular SQL database will also work?
- You have to install Umbraco Deploy (Concorde) manually. Is this just temporary, will there be a NuGet package available in the near future?
- If I understand this task correctly it commits the output into the UaaS repository. But is it then still possible to transfer content from UaaS to the local environment? Or does it take some additional steps?
- When will the task become available in the VSTS Marketplace? What needs to be done before you consider it as stable?

Thanks to clarify these issues for me.

**Comment by sitereactor** [comment]
Alright, I'll try and clarify. Let me know if it makes sense 😄 
1. The documentation on OUR is a specific approach for working with Visual Studio through a Website project. That is not how you would work with Visual Studio and this type of deployment. This VSTS task is intended for Developers who create Web Applications in VS and have Umbraco installed through nuget. So in terms of other projects, you can do pretty much what you like. You can add multiple class libraries to your solution. The only thing you should note is that the build output of the Web Application is what will be deployed, so set your references accordingly.
2. We recommend using Sql CE when working locally, because its a really nice approach to having an isolated database with no dependencies on Sql Server, etc. With Sql Ce we can ensure that everything is configured locally as you start the site. If you use a local sql server you have to manually install Umbraco, and that could be somewhat of a challenge if the user does not match your user on Umbraco as a Service. So I would still recommend using Sql Ce locally. You can use Sql Server if you really really want to, but it should not be shared with other developers of the same site.
3. Yes, its temporary for now because Umbraco Deploy is not available on NuGet. There are some licensing challenges that has to be sorted first.
4. Yes, you can still transfer Content and Media from your local environment to UaaS and you can also restore from UaaS. All schema parts like Document Types, Data Types, etc must be created locally though, as you have everything contained within your own git repository. But you can still have multiple Developers create and push Document Types to your own git repository and that will all work, and when its deployed to UaaS it'll also work there.
5. We have a bunch of work to do before this will be "Live" and added to the VSTS Marketplace. Its mainly the task of pushing updates back to your git repository. So, whenever we do autoupgrades of Umbraco or any of its dependencies like Forms or Deploy, we need to ensure that its also updated in your git repository, so you would connect your git repository with your project and we would then send updates through Pull Requests.

Hope this makes sense. Maybe check out my session from CodeGarden - I cover this task towards the end, and maybe it makes more sense to see it in action: [https://vimeo.com/channels/codegarden16/183623105](https://vimeo.com/channels/codegarden16/183623105)

**Comment by stiefdirckx** [comment]
@sitereactor Thank you very much for your comprehensive response. It certainly makes sense. And I will watch the CG video as soon as possible.

I understand the missing link with this task is the automatic Umbraco updating UaaS provides. So for now you have to repeat them yourself in your own VSTS repository to keep both repos in line with each other?

**Comment by sitereactor** [comment]
Yes, that manual step is required as long as we don't have a service in place to do that automatically 😄

**Comment by alexbechmann** [comment]
@steif - could a temporary solution be a webhook? Then we can wrote some code to update our repository ourselves ?

**Comment by stiefdirckx** [comment]
@alexbechmann I never worked with webhooks before so I don't know if you are able to define a webhook on the Umbraco Cloud project's Git repository.

**Comment by alexbechmann** [comment]
Sorry @steif i meant to tag @sitereactor - could it be possible to get a webhook so that we can implement our own code to perform the updates ourself on VSTS repo?

**Comment by sitereactor** [comment]
A webhook in Umbraco Cloud that is triggered whenever we apply an upgrade to a project?

**Comment by alexbechmann** [comment]
@sitereactor Yeah could that be possible?

**Comment by sitereactor** [comment]
I can't really promise anything, but you have given me an idea, which I'll try and work with on an upcoming 'freedom friday' :)

**Comment by alexbechmann** [comment]
@sitereactor awesome sounds intriguing :D
